#ifndef CONSTANTES_H
#define CONSTANTES_H

#endif // CONSTANTES_H

#define MATCH_METHOD 0
#define CAMERA_NUM -1
#define DELAY_BETWEEN_FRAMES_MS 25
#define FRAMES_PER_IMAGE_TBB 4
#define MATCH_NORMAL 0
#define MATCH_TBB 1
