#ifndef CONSTANTES_H
#define CONSTANTES_H

const int CODIGO_INICIAR_CAPTURA = 0;
const int CODIGO_INICIAR_VENTANA_AJUSTES = 1;
const int CODIGO_MOSTRAR_IMAGENES_RECORRIDO = 2;
const int CODIGO_CAMBIO_EROSION = 3;
const int CODIGO_RESET_IZQ = 4;
const int CODIGO_RESET_DER = 5;
const int CODIGO_CAMBIO_HSV_IZQ = 6;
const int CODIGO_CAMBIO_HSV_DER = 7;
const int CODIGO_MOSTRAR_CAM_HSV = 8;

const int CAMARA_UTILIZADA = 1;
const int DELAY_FRAME_CAMARA_MILI_SEG = 15;

#endif // CONSTANTES_H
